### ISSUE TITLE
Add featured videos and channels

### ISSUE THREAD

**Issue by pdxryanpdx** [WarzoneMC/website#44]

**Comment by dependants** [comment]
Are you talking about adding a category for media advertisement or creating a widget on the forums for featured videos + channels?

**Comment by Nuggets1** [comment]
This really isn't needed.

**Comment by Nuggets1** [comment]
After further discussion with Benny & Ryan, I do think that this feature should be added too the discord server due to the forums are not really used much apart from appeals/reports. If you do add this @BennyDoesTheStuff, you'll need to get staff actively checking this out making sure there is no pornography or anything that people under the age of 18 should be viewing.
